estimateRegistryPointPrevalence <- function(cdm,
                                    denominatorTableName,
                                    outcomeTable,
                                    denominatorCohortId = NULL,
                                    outcomeCohortId = NULL,
                                    timePoint = "start",
                                    minCellCount = 5) {


  estimateRegistryPrevalence(
    cdm = cdm,
    denominatorTableName = denominatorTableName,
    outcomeTable = outcomeTable,
    denominatorCohortId = denominatorCohortId,
    outcomeCohortId = outcomeCohortId,
    type = "point",
    interval = "years",
    timePoint = timePoint,
    minCellCount = minCellCount
  )
}


#' Estimate period prevalence for disease registries
#'
#' @param cdm A CDM reference object
#' @param denominatorTable A table in the cdm with denominator counts, 
#' typically generated by "getRegistryDenominator()"
#' @param outcomeTable A cohort table in the cdm reference containing
#' a set of outcome cohorts.
#' @param denominatorCohortId The definition ids of the denominator
#' counts of interest. If NULL all ids will be considered in the
#' analysis.
#' @param outcomeCohortId The cohort definition ids of the outcome
#' cohorts of interest. If NULL all cohorts will be considered in the
#' analysis.
#' @param interval Time intervals over which incidence is estimated. Can
#' be "years", or "overall" (from earliest cohort start to last cohort end). 
#' @param minCellCount Minimum number of events to report- results
#' lower than this will be obscured. If NULL all results will be reported.
#'
#' @return  Period prevalence estimates
#' @export
#'
estimateRegistryPeriodPrevalence <- function(cdm,
                                     denominatorTableName,
                                     outcomeTable,
                                     denominatorCohortId = NULL,
                                     outcomeCohortId = NULL,
                                     interval = "years",
                                     minCellCount = 5) {

  estimateRegistryPrevalence(
    cdm = cdm,
    denominatorTableName = denominatorTableName,
    outcomeTable = outcomeTable,
    denominatorCohortId = denominatorCohortId,
    outcomeCohortId = outcomeCohortId,
    type = "period",
    interval = interval,
    timePoint = "start",
    minCellCount = minCellCount
  )
}

estimateRegistryPrevalence <- function(cdm,
                               denominatorTableName,
                               outcomeTable,
                               denominatorCohortId = NULL,
                               outcomeCohortId = NULL,
                               type = "point",
                               interval = "years",
                               timePoint = "start",
                               # strata = list(),
                               # includeOverallStrata = TRUE,
                               minCellCount = 5) {

  startCollect <- Sys.time()

  # help to avoid formatting errors
  if (is.character(type)) {
    type <- tolower(type)
  }
  if (is.character(interval)) {
    interval <- tolower(interval)
  }
  if (is.character(timePoint)) {
    timePoint <- tolower(timePoint)
  }

  #Get denominator counts
  if (!omopgenerics::isTableEmpty(cdm[[denominatorTableName]])){
    # if not given, use all denominator and outcome cohorts
    if (is.null(denominatorCohortId)) {
      denominatorCohortId <- cdm[[denominatorTableName]] %>%
        dplyr::filter(!is.na(population) & population > 0 ) %>%
        dplyr::distinct(cohort_definition_id) %>%
        dplyr::pull("cohort_definition_id") %>% 
        sort()
    }
    
    denominatorTable <- cdm[[denominatorTableName]] %>%
      dplyr::filter(cohort_definition_id %in% denominatorCohortId) %>% 
      dplyr::collect()
    
    #Assuming complete years
    studyStartEnd = denominatorTable %>%
      summarise(max= as.Date(paste0(max(.data$year), "-12-31")),
                min= as.Date(paste0(min(.data$year), "-01-01")))
    
    denominator_settings <- denominatorTable %>%
      select(-population, -year) %>%
      mutate(cohort_name = paste0("denominator_cohort_", cohort_definition_id),
             days_prior_observation = 0,
             start_date = studyStartEnd$min,
             end_date = studyStartEnd$max) %>%
      distinct()
  }


  if (is.null(outcomeCohortId)) {
    outcomeCohortId <- omopgenerics::cohortCount(cdm[[outcomeTable]]) %>%
      dplyr::pull("cohort_definition_id")
  }

  outcomeRef <- omopgenerics::settings(cdm[[outcomeTable]]) %>%
    dplyr::filter(.env$outcomeCohortId %in% .data$cohort_definition_id) %>%
    dplyr::collect("cohort_definition_id", "cohort_name") %>%
    dplyr::rename("outcome_cohort_id" = "cohort_definition_id",
                  "outcome_cohort_name" = "cohort_name")

  if(nrow(outcomeRef) == 0){
    cli::cli_abort(message = c("Specified outcome IDs not found in the cohort set of
                    {paste0('cdm$', outcomeTable)}",
                               "i" = "Run CDMConnector::cohort_set({paste0('cdm$', outcomeTable)})
                   to check which IDs exist"))
  }
  
  # Check outcome table columns
  requiredCols <- c("cohort_definition_id", "subject_id", "cohort_start_date", 
                    "cohort_end_date", "age_gr", "sex")
  missingCols <- setdiff(requiredCols, colnames(cdm[[outcomeTable]]))

  if (length(missingCols) > 0) {
    errorCondition(paste0(
      "The following required columns are missing from outcome table: ",
      paste(missingCols, collapse = ", ")
    ))
  }

  studySpecs <- tidyr::expand_grid(
    outcomeCohortId = outcomeCohortId,
    denominatorCohortId = denominatorCohortId,
    interval = interval,
    timePoint = timePoint,
    fullContribution = FALSE,
    completeDatabaseIntervals = TRUE
  )

  studySpecs <- studySpecs %>%
    dplyr::mutate(analysis_id = as.character(dplyr::row_number()))

  studySpecs <- split(
    studySpecs,
    studySpecs[, c("analysis_id")]
  )

  tablePrefix <- paste0(
    paste0(sample(x = letters, size = 5, replace = TRUE), collapse = ""),
    type,
    "_prev"
  )

  # get prs
  counter <- 0
  prsList <- lapply(studySpecs, function(x) {
    counter <<- counter + 1
    message(glue::glue(
      "Getting prevalence for analysis {counter} of {length(studySpecs)}"
    ))

    workingPrev <- getRegistryPrevalence(
      cdm = cdm,
      denominatorTable = denominatorTable,
      denominatorCohortId = x$denominatorCohortId,
      outcomeTable = outcomeTable,
      outcomeCohortId = x$outcomeCohortId,
      type = type,
      interval = x$interval,
      timePoint = x$timePoint,
      tablePrefix = tablePrefix,
      analysisId = x$analysis_id
    )

    if (nrow(workingPrev[["pr"]]) == 0) {
      workingPrevPr <- dplyr::tibble()
    } else {
      workingPrevPr <- workingPrev[["pr"]] %>%
        dplyr::mutate(analysis_id = x$analysis_id) %>%
        dplyr::relocate("analysis_id")
    }

    workingPrevAnalysisSettings <- dplyr::tibble(
      analysis_id = x$analysis_id,
      outcome_cohort_id = x$outcomeCohortId,
      denominator_cohort_id = x$denominatorCohortId,
      analysis_type = paste0(.env$type, " prevalence"),
      analysis_interval = x$interval,
      analysis_complete_database_intervals = x$completeDatabaseIntervals,
      analysis_time_point = x$timePoint,
      analysis_full_contribution = x$fullContribution,
      analysis_min_cell_count = minCellCount
    )

    workingPrevAttrition <- workingPrev[["attrition"]] %>%
      dplyr::mutate(analysis_id = x$analysis_id) %>%
      dplyr::relocate("analysis_id")

    result <- list()
    result[["pr"]] <- workingPrevPr
    result[["analysis_settings"]] <- workingPrevAnalysisSettings
    result[["attrition"]] <- workingPrevAttrition

    return(result)
  })

  prsList <- purrr::flatten(prsList)

  # analysis settings
  analysisSettings <- prsList[names(prsList) == "analysis_settings"]
  analysisSettings <- dplyr::bind_rows(analysisSettings,.id = NULL)

  analysisSettings <- analysisSettings %>%
    dplyr::left_join(
      # omopgenerics::settings(cdm[[denominatorTable]]) %>%
      denominator_settings %>%
        dplyr::rename("cohort_id" = "cohort_definition_id") %>%
        dplyr::rename_with(
          .cols = dplyr::everything(),
          function(x) {
            paste0("denominator_", x)
          }
        ),
      by = "denominator_cohort_id"
    )


  attrition <- prsList[names(prsList) == "attrition"]
  attrition <- dplyr::bind_rows(attrition,.id = NULL ) %>%
    # dplyr::select(-"denominator_cohort_id") %>%
    dplyr::relocate("analysis_id")

  CDMConnector::dropTable(
    cdm = cdm,
    name = dplyr::starts_with(paste0(tablePrefix, "_analysis_"))
  )

  # prevalence estimates
  prs <- prsList[names(prsList) == "pr"]
  prs <- dplyr::bind_rows(prs,.id = NULL)

  # get confidence intervals
  if (nrow(prs) > 0) {
    prs <- prs %>%
      dplyr::relocate("prevalence_start_date", .after = "analysis_id") %>%
      dplyr::relocate("prevalence_end_date", .after = "prevalence_start_date")

    prs <- prs %>%
      dplyr::bind_cols(binomialCiWilson(
        prs$n_cases,
        prs$n_population
      )) %>%
      dplyr::relocate("prevalence_95CI_lower", .after = "prevalence") %>%
      dplyr::relocate("prevalence_95CI_upper", .after = "prevalence_95CI_lower")

  }

  # attrition summary
  attrition <- prsList[names(prsList) == "attrition"]
  # to tibble
  attrition <- dplyr::bind_rows(attrition,.id = NULL) %>%
    # dplyr::select(-"denominator_cohort_id") %>%
    dplyr::relocate("analysis_id")
  # obscure counts
  attrition <- obscureAttrition(attrition, minCellCount = minCellCount)

  analysisSettings <- analysisSettings %>%
    dplyr::left_join(outcomeRef, by = "outcome_cohort_id") %>%
    dplyr::relocate("outcome_cohort_name", .after = "outcome_cohort_id") %>%
    dplyr::relocate("denominator_cohort_id", .after = "analysis_min_cell_count") %>%
    dplyr::mutate(cdm_name = attr(cdm, "cdm_name"))

  # summarised result
  ## settings
  analysisSettings <- analysisSettings |>
    dplyr::mutate(
      result_id = as.integer(.data$analysis_id),
      result_type = "prevalence",
      package_name = "IncidencePrevalenceRegistries",
      package_version = "1.0.0"
    ) |>
    dplyr::select(!dplyr::ends_with("_cohort_id")) |>
    dplyr::select(!dplyr::ends_with("_cohort_definition_id")) |>
    dplyr::select(c(
      "result_id", "result_type", "package_name", "package_version",
      "analysis_type", "analysis_interval",
      "analysis_complete_database_intervals", "analysis_full_contribution"),
      dplyr::starts_with("denominator_"), dplyr::starts_with("outcome_")
    )
    ## result
    if (!"strata_name" %in% colnames(prs)) {
      prs <- prs |>
        visOmopResults::uniteStrata()
    }

    if(nrow(prs) == 0){
      prs <- omopgenerics::emptySummarisedResult()
    } else {
      prs <- prs |>
        dplyr::distinct() |>
        dplyr::mutate("analysis_id" = as.integer(.data$analysis_id)) |>
        dplyr::rename(
          "result_id" = "analysis_id",
          "outcome_count" = "n_cases",
          "denominator_count" = "n_population"
        ) |>
        dplyr::left_join(
          analysisSettings |>
            dplyr::select(c(
              "result_id", "denominator_cohort_name", "outcome_cohort_name", "analysis_interval"
            )),
          by = "result_id"
        ) |>
        visOmopResults::uniteGroup(c("denominator_cohort_name")) |>
        visOmopResults::uniteAdditional(cols = c("prevalence_start_date", "prevalence_end_date", "analysis_interval")) |>
        dplyr::rename("variable_level" = "outcome_cohort_name") |>
        dplyr::mutate("variable_name" = "outcome_cohort_name") |>
        dplyr::mutate(
          outcome_count = as.numeric(outcome_count), 
          denominator_count =as.numeric(denominator_count) 
          ) |>
        tidyr::pivot_longer(
          cols = c("denominator_count", "outcome_count", "prevalence",
                   "prevalence_95CI_lower", "prevalence_95CI_upper"),
          names_to = "estimate_name",
          values_to = "estimate_value"
        ) |>
        dplyr::mutate(
          "estimate_value" = as.character(.data$estimate_value),
          "estimate_type" = dplyr::if_else(
            grepl("count", .data$estimate_name), "integer", "numeric"
          ),
          "cdm_name" = attr(cdm, "cdm_name"),
          "strata_name" = dplyr::if_else(.data$strata_name == "Overall", "overall", gsub(" and ", " &&& ", .data$strata_name)),
          "strata_level" = dplyr::if_else(.data$strata_level == "Overall", "overall", gsub(" and ", " &&& ", .data$strata_level))
        )
    }

    prs <- omopgenerics::newSummarisedResult(
      x = prs,
      settings = analysisSettings |> dplyr::select(!c("denominator_cohort_name")) |>
        dplyr::mutate(dplyr::across(-"result_id", as.character))
      # settings = analysisSettings |> dplyr::select(!c("denominator_cohort_name", "outcome_cohort_name")) |>
      #   dplyr::mutate(dplyr::across(-"result_id", as.character))
    )

    attritionSR <- attrition |>
      dplyr::distinct() |>
      dplyr::mutate("analysis_id" = as.integer(.data$analysis_id)) |>
      dplyr::rename(
        "result_id" = "analysis_id",
      ) |>
      dplyr::left_join(
        analysisSettings |>
          dplyr::select(c(
            "result_id", "denominator_cohort_name", "outcome_cohort_name"
          )),
        by = "result_id"
      ) |>
      dplyr::rename(
        "variable_level" = "outcome_cohort_name"
      ) |>
      visOmopResults::uniteGroup("denominator_cohort_name") |>
      tidyr::pivot_longer(
        cols = c(
          "number_records", "number_subjects", "excluded_records",
          "excluded_subjects"
        ),
        names_to = "variable_name",
        values_to = "estimate_value"
      ) |>
      dplyr::mutate(
        "estimate_name" = "count",
        "estimate_value" = as.character(.data$estimate_value),
        "estimate_type" = "integer",
        "cdm_name" = attr(cdm, "cdm_name")
      ) |>
      visOmopResults::uniteStrata("reason") |>
      visOmopResults::uniteAdditional("reason_id") |>
      dplyr::relocate(omopgenerics::resultColumns()) |>
      omopgenerics::newSummarisedResult(settings = analysisSettings |>
                                          dplyr::select(!c("denominator_cohort_name")) |>
                                          dplyr::mutate(result_type = "prevalence_attrition") |>
                                          dplyr::mutate(dplyr::across(-"result_id", as.character)))

    prs <- omopgenerics::bind(prs, attritionSR) |>
      omopgenerics::suppress(minCellCount = minCellCount)



  dur <- abs(as.numeric(Sys.time() - startCollect, units = "secs"))
  message(glue::glue(
    "Time taken: {floor(dur/60)} mins and {dur %% 60 %/% 1} secs"
  ))

  return(prs)
}

binomialCiWilson <- function(x, n) {
  alpha <- 0.05
  p <- x / n
  q <- 1 - p
  z <- stats::qnorm(1 - alpha / 2)
  t1 <- (x + z^2 / 2) / (n + z^2)
  t2 <- z * sqrt(n) / (n + z^2) * sqrt(p * q + z^2 / (4 * n))
  return(dplyr::tibble(
    prevalence_95CI_lower = t1 - t2,
    prevalence_95CI_upper = t1 + t2
  ))
}
